### PR TITLE
Fix php8.1 deprecations, run tests on php8.1

### PR DESCRIPTION
**Pull request by bastien-phi**
Another way to fix the deprecations in to add return types.

Let me know if you prefer this way

### CODE REVIEW

**Comment by mdumoulin** [comment]
Hi @msarca @sorinsarca and thanks @bastien-phi. The fix seems alright to me and similar to chosen solution in json-schema : https://github.com/opis/json-schema/pull/96. Can we expect a merge soon ?

**Comment by sorinsarca** [comment]
Released in v2.0.1

**Comment by mdumoulin** [comment]
@sorinsarca Thanks !

**Comment by matiux** [comment]
Same error with opis/string  2.0.1 

```
  1x: Method "ArrayAccess::offsetSet()" might add "void" as a native return type declaration in the future. Do the same in implementation "Opis\String\UnicodeString" now to avoid errors or add an explicit @return annotation to suppress this message.

  1x: Method "ArrayAccess::offsetUnset()" might add "void" as a native return type declaration in the future. Do the same in implementation "Opis\String\UnicodeString" now to avoid errors or add an explicit @return annotation to suppress this message.
```

**Comment by ricky-rockstar** [comment]
> Same error with opis/string 2.0.1
> 
> ```
>   1x: Method "ArrayAccess::offsetSet()" might add "void" as a native return type declaration in the future. Do the same in implementation "Opis\String\UnicodeString" now to avoid errors or add an explicit @return annotation to suppress this message.
> 
>   1x: Method "ArrayAccess::offsetUnset()" might add "void" as a native return type declaration in the future. Do the same in implementation "Opis\String\UnicodeString" now to avoid errors or add an explicit @return annotation to suppress this message.
> ```

Is this going to be fixed?

**Pull request merged**
